In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('/content/Churn_Modelling.csv')

In [4]:
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
dataset.shape

(10000, 14)

In [6]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
dataset.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [8]:
X = pd.DataFrame(dataset.iloc[:, 3:13].values)
y = dataset.iloc[:, 13].values

In [9]:
X

        0        1       2   3   4          5  6  7  8          9
0     619   France  Female  42   2        0.0  1  1  1  101348.88
1     608    Spain  Female  41   1   83807.86  1  0  1  112542.58
2     502   France  Female  42   8   159660.8  3  1  0  113931.57
3     699   France  Female  39   1        0.0  2  0  0   93826.63
4     850    Spain  Female  43   2  125510.82  1  1  1    79084.1
...   ...      ...     ...  ..  ..        ... .. .. ..        ...
9995  771   France    Male  39   5        0.0  2  1  0   96270.64
9996  516   France    Male  35  10   57369.61  1  1  1  101699.77
9997  709   France  Female  36   7        0.0  1  0  1   42085.58
9998  772  Germany    Male  42   3   75075.31  2  1  0   92888.52
9999  792   France  Female  28   4  130142.79  1  1  0   38190.78

[10000 rows x 10 columns]

In [10]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [11]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_2 = LabelEncoder()
X.loc[:, 2] = labelencoder_X_2.fit_transform(X.iloc[:, 2])

In [12]:
X.loc[:,2]

0       0
1       0
2       0
3       0
4       0
       ..
9995    1
9996    1
9997    0
9998    1
9999    0
Name: 2, Length: 10000, dtype: int64

In [13]:
labelencoder_X_1 = LabelEncoder()
X.loc[:, 1] = labelencoder_X_1.fit_transform(X.iloc[:, 1])

In [14]:
X.iloc[:,1]

0       0
1       2
2       0
3       0
4       2
       ..
9995    0
9996    0
9997    0
9998    1
9999    0
Name: 1, Length: 10000, dtype: int64

In [15]:
onehotencoder = OneHotEncoder(categories='auto')
labelencoder_X_1 = LabelEncoder()

#onehotencoder = OneHotEncoder(categorical_features = [1])
#labelencoder_X_1 = LabelEncoder()


X.loc[:, 1] = labelencoder_X_1.fit_transform(X.iloc[:, 1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
import tensorflow as tf
import keras

from keras.models import Sequential
from keras.layers import Dense

In [19]:
classifier = Sequential()

In [20]:
classifier.add(Dense(units = 11 , kernel_initializer = 'uniform' , activation = 'relu'))

In [21]:
classifier.add(Dense(units =4, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 4, kernel_initializer = 'uniform', activation = 'relu'))

In [22]:
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [23]:
#Compile ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [38]:
classifier.fit(X_train, y_train, batch_size = 42, epochs = 30)

Epoch 1/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0845 - accuracy: 0.9784
Epoch 2/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0792 - accuracy: 0.9801
Epoch 3/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0765 - accuracy: 0.9803
Epoch 4/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0743 - accuracy: 0.9804
Epoch 5/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0725 - accuracy: 0.9805
Epoch 6/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0712 - accuracy: 0.9805
Epoch 7/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0701 - accuracy: 0.9805
Epoch 8/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0693 - accuracy: 0.9805
Epoch 9/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0686 - accuracy: 0.9805
Epoch 10/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0681 - accuracy: 0.9805
Epoch 11/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0674 - accuracy: 0.9806
Epoch 12/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0670 - accuracy: 0.9806
Epoch 13/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0668 - accuracy: 0.9806
Epoch 14/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0665 - accuracy: 0.9806
Epoch 15/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0664 - accuracy: 0.9806
Epoch 16/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0663 - accuracy: 0.9806
Epoch 17/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0662 - accuracy: 0.9806
Epoch 18/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0661 - accuracy: 0.9806
Epoch 19/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0660 - accuracy: 0.9806
Epoch 20/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0660 - accuracy: 0.9806
Epoch 21/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0660 - accuracy: 0.9806
Epoch 22/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0659 - accuracy: 0.9806
Epoch 23/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0659 - accuracy: 0.9806
Epoch 24/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0659 - accuracy: 0.9806
Epoch 25/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0659 - accuracy: 0.9806
Epoch 26/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0659 - accuracy: 0.9806
Epoch 27/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0659 - accuracy: 0.9806
Epoch 28/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0659 - accuracy: 0.9806
Epoch 29/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0659 - accuracy: 0.9806
Epoch 30/30
191/191 [==============================] - 1s 4ms/step - loss: 0.0659 - accuracy: 0.9806

In [39]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1595    0]
 [ 404    1]]

0.798

In [41]:
accuracy_score(y_pred,y_test)

0.798

In [33]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping
early_stop = EarlyStopping(monitor='val_loss')

In [ ]:
model= Sequential()
model.add(Dense(units=4,activation='relu',kernel_initializer='he_uniform'))

model.add(Dense(units=4,activation='relu',kernel_initializer='he_uniform'))
model.add(Dense(units=4,activation='relu',kernel_initializer='he_uniform'))
model.add(Dense(units=1,activation='None',kernel_initializer="glorot_uniform"))
model.compile(optimizer='adam',loss="binary_crossentropy",metrics=['accuracy'])

model.fit(X_train,y_train,batch_size=10,validation_split=0.01,epochs=30,validation_data=(X_test,y_test),callbacks=[early_stop])

In [37]:
accuracy_score(y_pred,y_test)

0.798